name: OWASP ZAP Baseline Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.7.0
      with:
        target: 'https://careerkit.indstack.com/'

    - name: Upload ZAP Reports
      uses: actions/upload-artifact@v3
      with:
        name: zap_reports
        path: |
          report_html.html
          report_json.json
          report_md.md

    - name: Send Email with Report
      uses: mattnotmitt/send-email@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.SMTP_USER }}
        password: ${{ secrets.SMTP_PASS }}
        subject: "OWASP ZAP Scan Report"
        body: "Hi,\n\nPlease find the attached OWASP ZAP scan report."
        to: ${{ secrets.SMTP_TO }}
        from: ${{ secrets.SMTP_USER }}
        secure: true
        attachments: report_html.html
