name: OWASP ZAP Baseline Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.7.0
      with:
        target: 'http://example.com'  # ← change this to your actual target

    - name: Upload ZAP Reports
      uses: actions/upload-artifact@v3
      with:
        name: zap_reports
        path: |
          report_html.html
          report_json.json
          report_md.md
